### ISSUE TITLE
Money duplication glitch ( /sell )

### ISSUE THREAD

**Issue by ZylusFTW** [promcteam/prorpgitems#1]
Found a bug. It registers the emerald in the GUI as an item that was put in there by the player to be sold. I think it's also applicable to anything in the worth.yml or the file where you set the value of an item.
![2021-04-23_15 06 56](https://user-images.githubusercontent.com/68259283/115867300-81bd7600-a46d-11eb-86a2-df2a2a374e0e.png)

**Comment by goflishMC** [comment]
Fixed in alpha dev build 1.0
