### ISSUE TITLE
[Enhancement]When will update 1.18 version support?

### ISSUE THREAD

**Issue by HuJunwei23333** [promcteam/prorpgitems#108]
This is the best RPG item plugin please don't give up updating it

**Comment by Travja** [comment]
It already has 1.18 support.

**Comment by HuJunwei23333** [comment]
I am a spigot server and have installed the latest versions of ProMCCore-1.0.3.1-ALPHA and ProRPGItems-1.0.3.3-ALPHA but it does not work

**Comment by HuJunwei23333** [comment]
> It already has 1.18 support.

I am a spigot server and have installed the latest versions of ProMCCore-1.0.3.1-ALPHA and ProRPGItems-1.0.3.3-ALPHA but it does not work

**Comment by goflishMC** [comment]
@HuJunwei23333 those are not the latest versions

download from here: https://www.spigotmc.org/resources/authors/goflish.21294/
