### ISSUE TITLE
[Bug]: The RANGE attribute cannot be used

### ISSUE THREAD

**Issue by 1470429149** [promcteam/prorpgitems#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use command  /qrpg set stat RANGE 1 ,When i add an attribute to an item, you are prompted that the attribute does not exist，I made sure I had the RANGE property switched on （in STATS.YML）
![Screenshot_2022-03-10-07-06-56-297_com x8zs sandbox](https://user-images.githubusercontent.com/96332168/157554727-e163c1dd-cfbd-47e2-a28e-3bc3d81a1de1.png)

### Expected Behavior

Fix RANGE failure

### Environment

```markdown
- Server Software: Paper Spigot 1.17.1
- ProRPGItems Version:1.0.3.14-0930442
- ProMCCore Version:1.0.3.7-0930442
```

**Comment by lordsrubka5** [comment]
I think range stat got removed couple versions back along with direct damage

**Comment by 1470429149** [comment]
> 我认为范围统计与直接伤害一起被删除了几个版本

Thank you for your answer.
