### ISSUE TITLE
[Bug]: Gem Removers on Consumables

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So turns out you can drag and drop gem extractors on consumables and they go poof

### Environment

```markdown
- Server Software:
- ProRPGItems Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
Jamm... I can't reproduce this 😭

**Comment by lordsrubka5** [comment]
Did you attempt with correct extractor?

The default ones ofc wouldnt work since they only target weapons and armors
```
target-requirements:
  type:
  - '*'
  level:
    '1': '1:15'
  module:
  - '*'
```
This would target all modules which also includes consumables I guess
Though that makes no sense since only item generator can have sockets as far as I know?
