### ISSUE TITLE
[Bug]: Not reading MythicMobs 5.11/other issue.

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/prorpgitems#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/88398845/187007973-0c8e7c8f-367d-4b9a-85d7-75254cc4e693.png)
![image](https://user-images.githubusercontent.com/88398845/187008010-95980f6a-acbb-4c54-9b63-76338e1e2eb4.png)

### Expected Behavior

Should be loading without issue, but noticed MM is not loading the dev version. Also noticed a null, that is causing it not to load into list.

### Environment

```markdown
- Server Software:
- ProRPGItems Version:latest
- ProMCCore Version:latest
- Plugins:
https://prnt.sc/dU2jyie2xYiB
```

**Comment by DrHeretic** [comment]
It does seem to be working via ingame with commands. Idk why its not green via /plugins

![image](https://user-images.githubusercontent.com/88398845/187008715-99168fca-d9df-483e-a16c-0cca80c7ad23.png)

**Comment by Travja** [comment]
You're running a quite old version of the plugin.

**Comment by DrHeretic** [comment]
That's odd I used the dev version, will check my files

**Comment by DrHeretic** [comment]
Seems to still be tossing those errors around. Seems for some reason its reading old RPGitems when I have the dev build in.

![image](https://user-images.githubusercontent.com/88398845/187009399-61efa869-5f84-454f-8b3f-1ddf75f0007e.png)
 
 Going to try removing/ reloading with out rpgitems in, then load it back in

**Comment by Travja** [comment]
The bugs you've posted show that you have old Core and old RPGItems

**Comment by DrHeretic** [comment]
That's the thing I'm posting this from dev builds from the discord.
![image](https://user-images.githubusercontent.com/88398845/187009650-b47d964e-12cc-4f76-98d8-0cc4bbf11aa0.png)
^ This is in the server.

![image](https://user-images.githubusercontent.com/88398845/187009666-7455e847-efbe-4fc6-b475-9a21b45e7cfe.png)

But it loads old.

**Comment by DrHeretic** [comment]
This is from recent restart with the most recent files in.

**Comment by Travja** [comment]
That's not the latest build. The latest builds should actually be on Spigot

**Comment by DrHeretic** [comment]
Oh ok, let me try the spigot ones.

**Comment by DrHeretic** [comment]
Issues  cleared, Thankyou
