### ISSUE TITLE
Damage Problems[Bug]

### ISSUE THREAD

**Issue by Hoshino2001** [promcteam/prorpgitems#13]
Set the damage in itemgenerator/customitem file will only increase the damage of the vanilla version. It will not become the damage value I want.

**Comment by goflishMC** [comment]
I'm adding more information to this bug report with my testing results.

my sword that i made in the item generator module does not do damage to mobs: https://i.imgur.com/8aCK2c6.png

https://i.imgur.com/CcHKqQY.png (this sword is doing zero damage even though it should be doing 5 physical damage)

https://i.imgur.com/qtb4gzu.png (this is adding 5 vanilla damage to my diamage sword for a total of 12 damage, it should be replacing the vanilla amount of 7 damage and doing only 5 damage instead). Even with 5 physical damage on this sword, it still only does the vanilla damage + the additional 5 vanilla damage I added in this example.

**Recap**
The plugin is not doing it's own custom damage.
When the vanilla damage is used in the item generator, it's not replacing the default vanilla damage, but adding to it.
