### ISSUE TITLE
[Bug]: MythicMob Custom Damage Modifiers Not Working

### ISSUE THREAD

**Issue by blackquiver** [promcteam/prorpgitems#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The damage modifiers for specific MythicMob factions doesn't work.

The entity-type modifier works fine, but there is zero change for the faction modifier.

### Expected Behavior

Damage is expected to change when the mob is in a specific faction.

### Environment

```markdown
- Server Software: Paper Spigot 1.18.2
- ProRPGItems Version: 1.1.7.16
- ProMCCore Version: 1.0.3.8
```

**Comment by Travja** [comment]
I'm not entirely sure what this means, or how you're expecting this to behave. I'm not super familiar with MythicMobs or the damage factions and how that should be handled. ProRPGItems jumps in between a lot of things as it is. Could you break down how the MythicMobs Factions are supposed to behave for me?

**Comment by blackquiver** [comment]
You can modify how much damage a custom damage type does to a mob, via the damage.yml configs in ProRPGItems.

You can set modifiers based on what biome you are in, what type a mob is, or what faction a MythicMob is set up to be.

Individual mobs in the MythicMob config files can be assigned to custom named factions.

Biome and mob type modifiers work, but the faction modifier does not.

**Comment by lordsrubka5** [comment]
Its bassically a classifier for a mob. It can be used in conditions to parse it for special effets in this case to deal extra damage only to specific groups of mobs.

Mythicmobs wise they can be used for bunch of other things like making two factions fight eachother or be friendly to players and what not

**Comment by goflishMC** [comment]
@Travja In mythicmobs mobs file you can set the mob to be of a custom faction name. Any mob that are not the same faction in mythicmobs that come within aggro distance will attack each other.

In rpgitems, in prorpgitems/plugins/item_stats/damage.yml you can set modifiers to mythicmobs factions

The modifiers work for the other options in that file, but not when used with the MM factions

**Comment by Travja** [comment]
This should be resolved working, at least as of the latest build today.
