### ISSUE TITLE
[Bug]: MythicDrops conflicting

### ISSUE THREAD

**Issue by Amyukxx** [promcteam/prorpgitems#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using ProRPGItems adding a Damage Gem to a weapon gives the gem back to the player 

### Expected Behavior

Damage Gem not given back to player

### Steps To Reproduce

1. Install MythicDrops 
2. Add Damage Gem to a weapon
3. Damage Gem given back to player

### Environment

```markdown
Server Software: Paper-1.19.2-177
- ProRPGItems Version:1.0.3.16-4050352
- ProMCCore Version:1.0.3.9-3421730
- Plugins:MythicDrops-8.3.6
```

**Comment by Travja** [comment]
I'm not entirely sure what you're running into here. Gems usually have charges, so adding a gem to a weapon consumes a charge. In the case where the gem is a single-use or has only one charge left, it should be consumed upon adding it to a weapon. This behavior should be independent of MythicDrops, but if there is a collision with MythicDrops, this feels like a really weird way for it to present itself.

**Comment by lordsrubka5** [comment]
I import gems to mythicmobs items and then drop a single charge gem and it works as intended. As long as it has proprgitems gems nbt tag it will work as intended
