### ISSUE TITLE
[Bug] Damage Porblem

### ISSUE THREAD

**Issue by GreenTeaChaCha** [promcteam/prorpgitems#14]
**Versions (please complete the following information):**
-  Spigot Version: 1.16.5-R0.1-SNAPSHOT
 - Server Version: 1.16.5
 - Plugin Version: 1.0.2-ALPHA

When added **STAT**(all) will make the weapon(sword,tools) can't hit other And it will turn the NTB to -1 Damage in mainhand.

**Comment by Travja** [comment]
Duplicates #9 Further updates will be posted there. This is likely an issue caused by changes in Reflection implementation in our recent update for 1.0.2.
