### ISSUE TITLE
[Bug]: Mimic can't get from ProRPGItems ClassManager

### ISSUE THREAD

**Issue by misery00** [promcteam/prorpgitems#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing ProRPGItems on the server, [Mimic](https://www.spigotmc.org/resources/mimic.82515/) (RPGInventory takes data from Mimic) breaks with an error in the screenshot. I wrote to the developers of Mimic, but they told me to write here.

Mimic selects a system of levels from ProRPGItems:
`registerService(BukkitLevelSystem.Provider.class, new ProRpgItemsLevelSystem.Provider());`

![изображение](https://user-images.githubusercontent.com/102464301/197168873-27fe9624-6229-4463-84ec-558de01c41b1.png)

And when Mimic tries to get the player's level, the error is in the ProRGPItems itself, since for some reason you commented out your ClassManager from which the level should be obtained

As a result, plugin get `null.getUserData(player)`, which is what the error says 

### Expected Behavior

Mimic should get a level from ProRPGItems, but can't. Everything is fine with ProSkillApi, the problem occurs only when installing ProRPGItems (nothing else needs to be done)

### Steps To Reproduce

1. Install ProRPGItems
2. Install MimicAPI
3. Install RPGInventory
4. RPGInv is broken because it takes data from Mimic

### Environment

```markdown
- Server Software: Purpur 1.18.2 (tried on Pufferfish 1.18.2 too)
- ProRPGItems Version: 1.0.3.16
- ProMCCore Version: 1.0.3.9
- Plugins: BKCommonLib, FastAsyncWorldEdit, LuckPerms, Mimic, PlaceholderAPI, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, RPGInventory, spark, Vault
```

### latest.log

[latest.log](https://github.com/promcteam/prorpgitems/files/9837981/latest.log)

**Comment by Sentropic** [comment]
The issue is here: https://github.com/promcteam/prorpgitems/commit/59c0cb7d1989c2019a13687e952f7cfdafa39e8d
