### ISSUE TITLE
[Bug] Defense For Vanilla Armor

### ISSUE THREAD

**Issue by fuxwa** [promcteam/prorpgitems#15]
**Describe the bug**
Hello, I'm having a problem
when the player wears vanilla armor, the damage reduction will be lost
i checked the physical armor but it's zero and i don't know what's going on
but when i add armor by command /qrpg set defense physical 10 the damage reduction worked
i want vanilla armor to work, how can i get it?
I use the default config, haven't edited anything

**latest.log**
https://pastebin.com/SUqqF1EC

**Versions (please complete the following information):**
-  Spigot Version: 1.16.5
 - Server Version: 1.16.5
 - Plugin Version: 1.0.2-ALPHA

**Comment by goflishMC** [comment]
Can you message me on discord about this issue, I'm not 100% sure what you are trying to say.

**Comment by fuxwa** [comment]
okay

**Comment by goflishMC** [comment]
> okay

what's your name on discord?

**Comment by fuxwa** [comment]
hello
https://www.youtube.com/watch?v=axriKAt4E5I
this is a bug i said
when i wear vanilla armor damage reduction doesn't work
when i add physical defense  damage reduction worked

**Comment by goflishMC** [comment]
I just tested this. With prorpgitems installed I did 7 damage to another player with and without diamond armor.

After removing prorpgitems I only did 0.5 damage to a player with diamond armor.

I was using an unmodified/unenechanted diamond sword.

**Comment by Travja** [comment]
I believe I tracked this down. We had removed the ability to add direct-damage to items a few iterations back and I mistakenly marked the default direct-damage in some of the other code as 100% causing all damage to bypass any type of armor.
