### ISSUE TITLE
[Enhancement] Random attribute rolls on items

### ISSUE THREAD

**Issue by gMithos** [promcteam/prorpgitems#154]
**Is your feature request related to a problem? Please describe.**
I'm not able to add attributes randomly generated onto items. I can manually type lets say Dexterity: 20 and skill api can pick it up from lore but there's no way to have rolls

**Describe the solution you'd like**
Be able to roll attributes onto items so skillapi can pick it up.
Being able to create new item stats related to skillapi attributes.
Like any other item stats rolled, you could be able to give a min and max to the desired attribute, with a % chance of being on the item, and it would return with a number between the min and max and be applied to the attribute directly.

**Comment by goflishMC** [comment]
If Proskilapi is detected it would add a new section in the item generator for Skillapi Attributes

<pre>
New file in item_stats folder called skillapi-attributes.yml
ATTRIBUTE_STRENGTH:
  enabled: true
  name: AoE Damage
  format: ' &7%name% &f%value%'
  capacity: -1

ATTRIBUTE_VITALITY:
  enabled: true
  name: PvP Damage
  format: ' &7%name% &f%value%'
  capacity: -1

ATTRIBUTE_DEXTERITY:
  enabled: true
  name: PvE Damage
  format: ' &7%name% &f%value%'
  capacity: -1
  

New section in item generator file
# The number rolled should be an integer
  skillapi-attributes:
    minimum: 1
    maximum: 5
    lore-format:
    - '%SKILLAPI_ATTRIBUTE_STRENGTH%'
    - '%SKILLAPI_ATTRIBUTE_VITALITY%'
    - '%SKILLAPI_ATTRIBUTE_DEXTERITY%'
    list:
      attribute_strength:
        chance: 100.0
        scale-by-level: 1.0
        min: 5.0
        max: 9.0
      attribute_vitality:
        chance: 100.0
        scale-by-level: 1.0
        min: 2.0
        max: 8.0
      attribute_dexterity:
        chance: 0.0
        scale-by-level: 1.0
        min: 2.5
        max: 4.0
</pre>

**Comment by lordsrubka5** [comment]
@goflishMC attributes cant be in decimals

**Comment by lordsrubka5** [comment]
Although fully adding support for it is ideal, if low on time maybe the faster solution might be adding papi support to the items so that we can use random number placeholder instead. It wouldnt have an option to roll a chance if the item gets an attribute or not but it will at least do the random number.

**Comment by goflishMC** [comment]
this is possible in the new in game editor
