### ISSUE TITLE
[Bug] this.plugin is null spam in the console 

### ISSUE THREAD

**Issue by TonyMontero** [promcteam/prorpgitems#16]
**Describe the bug**
A bug occurs when the plugin is fully loaded. It doesn't even require to use it to get this repetitive error going on.
Pastebin: https://pastebin.com/tWUbnXVn

**To Reproduce**
Just start the server using PaperMC lastest 1.17.1 build (116) and here it goes.

**latest.log**
https://pastebin.com/tWUbnXVn

**Versions (please complete the following information):**
-  PaperMC Version: 1.17.1 (build 116)
 - Server Version: 1.17.1
 - Plugin Version: Alpha 1.0.2

**Comment by Travja** [comment]
I may have changed a few things since this was posted, but I don't currently get this spamming the console. I'll post a build here within the next couple days for you to test to make sure that it's resolved.

**Comment by TonyMontero** [comment]
Sure, i'll test it when the dev build  gets out

**Comment by TonyMontero** [comment]
> I may have changed a few things since this was posted, but I don't currently get this spamming the console. I'll post a build here within the next couple days for you to test to make sure that it's resolved.

Adding some information, i can get the spamming by just installing the plugins in a PaperMC 1.17.1 build 137, it's pretty easy to reproduce to be honest

[lastest.log](https://github.com/promcteam/prorpgitems/files/6900390/lastest.log)

**Comment by goflishMC** [comment]
I also confirmed that this is a current bug, even in the latest dev build.

Here's what I get: https://pastebin.com/tAhxHbti

**Comment by Travja** [comment]
This should officially be fixed with the latest build that I've put together.
