### ISSUE TITLE
[Enhancement] Re-Roll Item Stats for Item Generator

### ISSUE THREAD

**Issue by JakeBat-H** [promcteam/prorpgitems#167]
Intended function: 
The ability to enter a blacksmith/reforge GUI and able to spend a customizable resource (item)/money to re-roll an items given stats (optionally, give the user the option to enable rerolling the item entirely withing the itemgenerator settings, or just the stats and not the name), with a configurable chance for the item to break, unless using a gemstone/some customizable resource to prevent it from breaking and/or lower the chance of it breaking.

**Comment by lordsrubka5** [comment]
copy of #163
