### ISSUE TITLE
[Bug] Damage Problem

### ISSUE THREAD

**Issue by GreenTeaChaCha** [promcteam/prorpgitems#17]
**Versions (please complete the following information):**
Spigot Version: 1.16.5-R0.1-SNAPSHOT
Server Version: 1.16.5
Plugin Version: 1.0.2-ALPHA

When added STAT(all) will make the weapons and tools can't hit other and it will turn the NTB to -1 Damage.

Tested Items that cannot do damage when added stat:
    - WOODEN_AXE
    - GOLDEN_AXE
    - IRON_AXE
    - DIAMOND_AXE
    - STONE_AXE
    - WOODEN_SWORD
    - GOLDEN_SWORD
    - IRON_SWORD
    - DIAMOND_SWORD
    - STONE_SWORD   
    - WOODEN_SHOVEL
    - GOLDEN_SHOVEL
    - IRON_SHOVEL
    - DIAMOND_SHOVEL
    - STONE_SHOVEL
    - WOODEN_PICKAXE
    - GOLDEN_PICKAXE
    - IRON_PICKAXE
    - DIAMOND_PICKAXE
    - STONE_PICKAXE
    - WOODEN_HOE
    - GOLDEN_HOE
    - IRON_HOE
    - DIAMOND_HOE
    - STONE_HOE
    - FISHING_ROD
    - SHEARS

**Comment by Travja** [comment]
Duplicates #9
