### ISSUE TITLE
[Bug]: Refine modules

### ISSUE THREAD

**Issue by croderdai** [promcteam/prorpgitems#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue 1: Refine item don't lost after used!

Issued 2: I want change Material of tome-item =  Enchanted_book to Diamond (but lost all when used it instead of losing 1). You can fix?
(Because I want it to be stackable = x64 item)

promccore-1.0.4-R0.2-20221217.064306-1
prorpgitems-1.0.4-R0.7-20221230.080735-1
proskillapi-1.1.8-R0.10-20221231.013237-1 

### Environment

```markdown
- Server Software:
- ProRPGItems Version:
- ProMCCore Version:
- Plugins:
```

**Comment by xMystik** [comment]
Refine item can be held on player's hand while the Refine GUI is open and can be placed back to the inventory
