### ISSUE TITLE
[Bug]: No damage from shears

### ISSUE THREAD

**Issue by MendR98** [promcteam/prorpgitems#175]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

No damage from shears and other custom weapons. like a block of stone. 
vanilla mobs don't take damage either. 

### Expected Behavior

I set it up in the same way as in Quantum RPG, everything worked there and here the configs are the same

### Steps To Reproduce

1. create random items
2. no damage on heat mobs 

### Environment

```markdown
- ProRPGItems Version: 1.0.4 R0.2-20221217.0643206
- ProMCCore Version: 1.0.4 R0.2-20221217.072200
- Plugins: MMobs
- Server Software: Paper 1.18.2 / spigot use.
```

### latest.log

No warn and reports

**Comment by Travja** [comment]
If you're still around, I just created an item through the item generator that was shears and damage works just fine. If you could try making sure you're up to date on your dev builds and try again? If it's still a problem, could you send me your configs so I can investigate further?

If I don't hear back in a bit, I'll just go ahead and close this, assuming that it's good to go.

**Comment by Travja** [comment]
I believe this was resolved with some changes Sentropic put in a bit ago.
