### ISSUE TITLE
[Bug]: This plugin and the CrackShot plugin have an impact on server performance

### ISSUE THREAD

**Issue by Ghost067** [promcteam/prorpgitems#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This plugin will listen to the CrackShot plugin when loading, and interact with this plugin when the bullet from the firearm made by CrackShot causes damage to the entity, resulting in serious performance vulnerability issues, I hope you can review the problem and release a fixed version as soon as possible.

### Expected Behavior

This plugin does not create performance vulnerabilities with CrackShot.

### Steps To Reproduce

Use CrackShot weapons to attack entities.

### Environment

```markdown
- Server Software: Paper1.16.5
- ProRPGItems Version: 1.0.4-R0.2-SNAPSHOT
- ProMCCore Version: 1.0.4-R0.2-SNAPSHOT
- Plugins: ProRPGItems ProRPGItems CrackShot CrackShotPlus
```

### latest.log

There are no conditions where the problem causes the server to crash.

### Anything else?

The Timings report generated by the server is here.
https://timings.aikar.co/dev/?id=f6c6f09d2e384783af008998591c01ab

**Comment by Travja** [comment]
It's not really even that it listens to CrackShot. The current implementation for damage overhauling inside ProRPGItems is honestly too robust and intrusive and creates these performance issues. I've done a decent amount to attempt to optimize this, but I feel that little more can be done without doing a full rewrite of the damage system. And that is not going to be a quick fix.

**Comment by Ghost067** [comment]
So are you going to refactor the plugin's damage system?
I hope you can fix this problem soon, this bug is affecting my server too much.

**Comment by Travja** [comment]
It's not going to happen soon, but it's on my list of things to do _eventually_

**Comment by goflishMC** [comment]
CrackShot is no longer supported. Anyone using crackshot needs to switch to the WeaponsMechanic plugin is supported by the team that made crackshot. 

I'm closing this issue. Make a new post if there's issues with the WeaponsMechanic plugin.
