### ISSUE TITLE
[Bug]: Gem and Rune dupe

### ISSUE THREAD

**Issue by Pfctink** [promcteam/prorpgitems#177]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When using a Gem or Rune, you have the item still in your inventory while it is on your mouse cursor, allowing anybody to press the "exit" button and put the item on their mouse into their inventory, creating an infinite supply of the same Gem/Rune

### Expected Behavior

I expect the item to not still be on my cursor while trying to socket them into another item.

### Steps To Reproduce

1. Obtain Gem or Rune
2. Obtain item to socket said Gem or Rune in
3. Socket the Gem or Rune into the item
4. Don't confirm the socket, instead exit the menu
5. You should now have duped Gem or Rune in your inventory

### Environment

```markdown
- Server Software: Paper 1.19.2
- ProRPGItems Version: prorpgitems-1.0.4-R0.4
- ProMCCore Version: promccore-1.0.4-R0.2
- Plugins: BetterShulkerBoxes, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), ChunkSpawnerLimiter, CombatLogX, CoreProtect, CraftingStore, Currencies, DecentHolograms, dynmap, Essentials, EssentialsSpawn, floodgate, Geyser-Spigot, Harbor, ItemJoin, LevelledMobs, LibsDisguises, LPC, LuckPerms, LuckyBounties, MedievalFactions, Minepacks, NoEncryption (ChatSignatures), PetDragon, PlaceholderAPI, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, Shopkeepers, SilkSpawners_v2, Simple-Drugs, SmoothTimber, SpawnStar, SuperVanish, TDRPlaytime*, Tether, Themis, TradeSystem, Trails, UberEnchant, UltimateChairs, VampireRevamp, VariableEnderChests, ViaBackwards, ViaVersion, voicechat, VotifierPlus, VotingPlugin, Vouchers, WarpSystem, WorldEdit, WorldEditSUI, WorldGuard
```

### latest.log

N/A, doesn't stop the server in any way that I know of, it's not detrimental to the server's health, but more of a gameplay balance issue.

**Comment by Travja** [comment]
This will actually be resolved with #174
