### ISSUE TITLE
[Bug]: /prorpgitems buff defense doesnt stack

### ISSUE THREAD

**Issue by SwimUp** [promcteam/prorpgitems#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I give 2 buffs:
/prorpgitems buff Defense physical 100 300
and then
/prorpgitems buff Defense physical 10000 300

But, player has only "100" buff 
Incoming damage does not change after receiving a second, larger buff

### Steps To Reproduce

1. Equip some armor (for example with 10 physical damage)
2. Give buff /prorpgitems buff Defense physical 100 30
3. Do damage
4. Give second buff Give buff /prorpgitems buff Defense physical 100-- 30
5. Do damage and you will see damage like after /prorpgitems buff Defense physical 100 30

### Environment

```markdown
- Server Software: Paper 1.19.3
- ProRPGItems Version: 1.0.4-R0.2-20221217.072200-1
- ProMCCore Version: 1.0.4-R0.2-20221217.064306-1
- Plugins: ProSkillAPI
```

**Comment by Travja** [comment]
What would be the preferred behavior here? Should it stack, effectively giving a buff of 10100? Or should the new one replace the existing buff?

**Comment by lordsrubka5** [comment]
preferably add an option like -r at the end of the command to "replace" the existing buff so we can use both methods
