### ISSUE TITLE
[Bug]: Repair Module - Repair Items Do Not Drop Down To 0 Charges And Disappear

### ISSUE THREAD

**Issue by blackquiver** [promcteam/prorpgitems#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following item in my Repair module. It will drop down to 1/10 charges, and then not use up any more charges. I want it to go to 0 and disappear, but it doesn't.

material: SADDLE
name: '&8Smiths Tools'
lore: 
  - '&7An assortment of hammers, tongs,'
  - '&7files, chisels and other smaller'
  - '&7tools that a smith may need.'
tier: common
level:
  min: 1
  max: 1
uses-by-level:
  '1': 10
repair-by-level:
  '1': 10
target-requirements:
  type:
  - '*'
  level:
  module:
  - '*'

### Expected Behavior

I expected the item to drop to 0 charges and disappear.

### Environment

```markdown
- Server Software: Spigot 1.18.2
- ProRPGItems Version: 1.0.3.17
- ProMCCore Version:1.0.4.1
```

**Comment by Travja** [comment]
Please grab the latest dev build from Discord and let me know if you're still experiencing this issue

**Comment by blackquiver** [comment]
Works now, apologies for wasting your time.
