### ISSUE TITLE
[Bug]: Custom Damage/Defense Not Working

### ISSUE THREAD

**Issue by blackquiver** [promcteam/prorpgitems#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have multiple damage and defense types on the armour and weapons on my server. They worked as intended when my server was launched, but at some point in the past (can't pinpoint a precise date), they no longer have any effect.

Mob damages vs players in armour does nothing
Armour with defense types do nothing against the same damage types.

I have tried varying defense values, protection factors, trying the default configs, nothing seems to work.

### Expected Behavior

Defense should have some impact on incoming damage of the same type. Everything is linked correctly in the configs, protection values were set properly, yet it's just all stopped working.

### Environment

```markdown
- Server Software: 1.18.2
- ProRPGItems Version: 1.0.4-R0.12-20230316.235211-1
- ProMCCore Version: 1.0.4-R0.4-20230116.094637-1
- Plugins: BKCommonLib, BlockRegen, BookNickAuthor*, Brewery, ChatRange*, Citizens, CoreProtect, CustomCrafting, DiscordSRV, Dorfroller, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), ItemEdit, ItemTag, LibsDisguises, LightCleaner, LuckPerms, MCCore*, Mimic, MorePlayerModels2, Multiverse-Core, Multiverse-Portals, MythicMobs, PlaceholderAPI, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, PsudoCommand, SavageDeathChest, VariableTime*, Vault, Votifier, VotingPlugin, WolfyUtilities, WorldGuard, WorldGuardExtraFlags

I have also tried various combinations of builds over the last couple months. None seem to solve the problem.
```

**Comment by blackquiver** [comment]
The damage modifiers against mobs work fine.

**Comment by Travja** [comment]
Player vs Player and Player vs Mob work fine, just Mob->Player has issues?

**Comment by blackquiver** [comment]
> Player vs Player and Player vs Mob work fine, just Mob->Player has issues?

Not quite. When it's JUST ProRPGItems, ProMCCore and MythicMobs enabled on the server, everything works fine.

When everything else is enabled, Player vs Player doesn't work, Mob vs Player doesn't work, but I believe Player vs Mob works fine.

Damage still occurs, but the defenses don't seem to affect anything.

I'm trying to go through my plugin list to see if it's a specific plugin, but I don't think it is. Based on some tests yesterday, the damage/defense stuff just seems to break when a number of different plugins are enabled.

**Comment by blackquiver** [comment]
It's not a specific plugin that seems to be causing the problems, it just seems to be occurring when random plugins are enabled, but some of those plugins are needed for my server.

Brewery, Essentials, CustomCrafting to name a few.

I've got to assume the problem is therefore within the ProRPGItems plugin itself, somewhere.

**Comment by goflishMC** [comment]
This should be fixed now by Sentropic. Anyone that was having this issue just needs to update to the latest promccore, prorpgitems and proskillapi if you are using it.
