### ISSUE TITLE
[Bug]: The attribute 'lore' added to the 'myshicmobs' item cannot be used

### ISSUE THREAD

**Issue by v8v8** [promcteam/prorpgitems#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Server Software:
- ProRPGItems Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
What does this mean? What are you trying to accomplish that you're not being able to?

**Comment by v8v8** [comment]
> 这是什么意思？你想完成什么你无法做到的事情？

Adding the attribute 'lore' to the myshicmobs item has no effect

**Comment by v8v8** [comment]
This is the item I wrote on mythicmobs, without a Damage
[test.txt](https://github.com/promcteam/prorpgitems/files/11632986/test.txt)
