### ISSUE TITLE
[Bug]: error after reload plugins

### ISSUE THREAD

**Issue by ronyan149** [promcteam/prorpgitems#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i coudn't use /clearinvent after i reload prorpgitems 

### Steps To Reproduce

*Before reload qrpg

>clearinvent gemk
[16:44:50] [Server thread/INFO]: CONSOLE issued server command: /clearinvent gemk
[16:44:50] [Server thread/INFO]: Error: Player not found.

*after reload qrpg

>clearinvent gemk
[16:44:58] [Server thread/INFO]: Unknown command. Type "/help" for help.
>clearinvent
[16:45:02] [Server thread/INFO]: Unknown command. Type "/help" for help.

### Environment

```markdown
- Server Software:spigot 1.19.2
- ProRPGItems Version:ProRPGItems v1.0.6-R0.3-SNAPSHOT
- ProMCCore Version:promccore-1.0.6-R0.1
- Plugins:LuckPerms, PlaceholderAPI, ProtocolLib, LibsDisguises, BetterPrefix, Zenchantments, Geyser-Spigot, Vault, WorldEdit, DecentHolograms, Essentials, WorldGuard, Multiverse-Core, MythicMobs, DeluxeMenus, LeaderMobs, NexEngine, EssentialsSpawn, AuthMe, ProMCCore, LWC, HoloMobHealth, PlayerPoints, SilkSpawners, RaidsPerRegion, ExcellentCrates, ProRPGItems (QuantumRPG), ProSkillAPI (SkillAPI), TAB
```

**Comment by Travja** [comment]
Is clearinvent a prorpgitems command? Or a command from another plugin?

**Comment by ronyan149** [comment]
> Is clearinvent a prorpgitems command? Or a command from another plugin?

I use /clearinvent of essentialsX 2.21

**Comment by Travja** [comment]
Are you reloading using `/qrpg reload`, Spigot's reload command, or something like plugman?
