### ISSUE TITLE
[Bug]: module-item_hints-glow is not working at 1.20.1

### ISSUE THREAD

**Issue by fengbinggan** [promcteam/prorpgitems#195]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Server Software: 1.20.1-129
- ProRPGItems Version: 1.0.6-R0.7
- ProMCCore Version: 1.0.6-R0.6
- don't have another plugins
```

### Anything else?

No problem when I run on 1.18 paper

**Comment by Travja** [comment]
I'll have to double check this! Most of our users tend to disable it anyway, so I'm glad you spotted it!
