### ISSUE TITLE
[Bug]: WITHERSKELETON don't work at modules\loot\settings entity-blacklist

### ISSUE THREAD

**Issue by fengbinggan** [promcteam/prorpgitems#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't ban the loot for WITHERSKELETON

entity-blacklist:
  - WITHERSKELETON
  - WITHER_SKELETON
is not work

### Environment

```markdown
- Server Software: 1.20.1-129
- ProRPGItems Version: 1.0.6-R0.7
- ProMCCore Version: 1.0.6-R0.6
- Plugins:
```

**Comment by Travja** [comment]
That should be working… that's strange

**Comment by fengbinggan** [comment]
Yes, I tested all the creatures, only it did not work

**Comment by Travja** [comment]
I was not able to reproduce this. Adding the wither skeleton to the blacklist results in items dropping normally, and not being stuck into a loot head
![image](https://github.com/promcteam/prorpgitems/assets/1574947/878149cd-ba34-413f-9991-33998f10a3a4)
