### ISSUE TITLE
[Bug]: BASE_ATTACK_SPEED is not generated on items

### ISSUE THREAD

**Issue by Pwnzeye** [promcteam/prorpgitems#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the item generator setting the BASE_ATTACK_SPEED stat to 100% does not work. And there is enough spaces for that stat to generate. The stat is not working when generating items.

### Expected Behavior

That the stat is applied to generated items.

### Environment

```markdown
- Server Software: Purpur 1.20.4
- ProRPGItems Version: Latest
- ProMCCore Version: Latest
- Plugins:
```

**Comment by Travja** [comment]
Are you saying that the stat is just missing from the item's lore, or that the stat is altogether not working?

**Comment by Pwnzeye** [comment]
The stat is not showing up on generated items using the /itemgen get command

**Comment by Pwnzeye** [comment]
But the stat can be added to items using the /qrpg set stat command

**Comment by Travja** [comment]
![image](https://github.com/promcteam/prorpgitems/assets/1574947/1e9b53af-3a09-4028-aba2-b7531cd5d484)
Mine worked fine. Make sure you have the line `%ITEM_STAT_BASE_ATTACK_SPEED%` in your item-stats lore-format section for your item.

**Comment by Pwnzeye** [comment]
The bug has been resolved. My bad
