### ISSUE TITLE
[Bug]about gems

### ISSUE THREAD

**Issue by DawnKnight2819** [promcteam/prorpgitems#24]
Hello!My english is poor,but I'v found a very serious problem about gems.When a player using GUI to set the gems to weapons or armors,if he put the gem into GUI first,then put his weapon or armor into GUI,he can ignore the limit of the number of sockets.So the player can use this bug to set countless gems onto his weapon or armor as he wish!
(Under normal circumstances,if the player put a weapon with no empty socket into GUI first,when he try to put a gem into GUI,the gem won't be successfully placed and he will be warned.)

**Comment by goflishMC** [comment]
Can you test this error, we did some updates with gems.
