### ISSUE TITLE
[Bug]: Error when giving item generator item

### ISSUE THREAD

**Issue by materialplane** [promcteam/prorpgitems#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get this error when trying to get an item from the item generator: https://paste.travja.dev/zigucudabe.properties

### Expected Behavior

I should get the item based on the command

### Steps To Reproduce

Give yourself an item generator item

### Environment

```markdown
- Server Software: 1.21.3
- Divinity Version: 1.0.2-R0.5
- Codex Version: codex-1.0.1-R0.10
- Plugins: https://i.imgur.com/HQgca3G.png
```

**Comment by Travja** [comment]
Can you send me your commonpaddedarmor?
