### ISSUE TITLE
[Bug]: Old stats cannot be changed after updating to the new version

### ISSUE THREAD

**Issue by Ghost067** [promcteam/prorpgitems#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I updated the version of the plugin from 1.0.1-R0.11-SNAPSHOT to 1.0.2-R0.6-SNAPSHOT, all the Divinity edited item Stats in the player's hand became invalid, and the durability of the weapon will be displayed as a new line at the bottom of the GUI.
![e57617bf6aa2c034027ecdf4e586d1f5](https://github.com/user-attachments/assets/6837353a-80e4-480c-90a1-0d52544fcd8b)

### Expected Behavior

After the update is completed, the stats display normally.

### Environment

```markdown
- Server Software: 1.16.5 PaperSpigot
- Divinity Version: 1.0.2-R0.6-SNAPSHOT
- Codex Version: 1.0.1-R0.11-SNAPSHOT
- Plugins: Only
```

**Comment by Travja** [comment]
Given that the item is not in English, I'm not entirely sure what I'm looking at. At first glance, it looks like things are appearing properly. What do you mean when you say that the stats are invalid?

**Comment by Ghost067** [comment]
Sorry, I have already turned off my computer and am ready to go to bed. I will send you a more detailed explanation tomorrow morning.

**Comment by Ghost067** [comment]
In this picture:
The stats circled above are a durability attribute that I added in the Divinity version 1.0.1-R0.11-SNAPSHOT.
The content circled below is a durability attribute that suddenly appeared when I updated the Divinity version to 1.0.2-R0.6-SNAPSHOT, and the durability attribute above is no longer updated at all.
What I mean is that after updating the plugin version, it seems that the properties previously set on the item cannot be updated anymore.
![113e1b3ccfb75ce8a486819301837bef](https://github.com/user-attachments/assets/74d3fa37-d690-4d90-9a26-b558c772cde2)

**Comment by Travja** [comment]
I tracked this down. The fix won't fix the format of the items, but it will prevent further items from breaking in this way. You'll just need to get the latest Codex build.

**Comment by Ghost067** [comment]
Sorry, updating the plugin version to 1.0.2-R0.13 still persists. Can you try to solve it again?

**Comment by Travja** [comment]
Like I said, it won't fix the formatting for items that were already broken, but any others would be unaffected.

**Comment by Travja** [comment]
Also just to confirm. You updated both Divinity and Codex?

**Comment by Ghost067** [comment]
Yes, all the plugin versions I used are the latest versions you posted on Discord.

**Comment by Travja** [comment]
And could you describe the behavior you're seeing now?

**Comment by Ghost067** [comment]
But this affects the normal operation of my server.
My server is an RPG server and I need to use these equipment as materials for upgrading, but this situation will make the system unable to recognize the materials.

**Comment by Ghost067** [comment]
> And could you describe the behavior you're seeing now?

When I use commands to change some of the properties that I originally set, I cannot modify them in the same position as the properties in the GUI. Instead, a new property will appear at the bottom of the GUI.
When the durability attribute decreases, a new attribute will also appear at the bottom of the GUI

**Comment by Travja** [comment]
Are these items that existed before upgrading and things breaking? Or are these newly generated items? How are you creating them?

It may also be helpful to get the `/data get @s SelectedItem` for the item.

**Comment by Ghost067** [comment]
These items already existed before the plugin upgrade. Use the/rpgi set command to set the properties and then use MythicMobs to save the items.
It shouldn't be an issue with MythicMobs saving items, as some unsaved projects may also experience this situation after plugin upgrades.

**Comment by Travja** [comment]
If these items were used on the newer builds of Divinity/Codex they're sort of stuck. Without some manual editing of the NBT, you probably aren't going to be able to remove the extra line and restore the original line back.

**Comment by Travja** [comment]
If you manually build them, you're going to have to walk me through exactly what you're doing

**Comment by materialplane** [comment]
This is why you should use the editor to make your items with **/itemgen edit**
