### ISSUE TITLE
[Enhancement] LevelledMobs Support

### ISSUE THREAD

**Issue by jwevans1989** [promcteam/prorpgitems#38]
**Describe the solution you'd like**
LevelledMobs is a mob levelling plugin with far more levelling options than MythicMobs. It would be great if it can also be officially supported as a mob levelling plugin for mob drops and things like that.

**Comment by goflishMC** [comment]
engine.yml needs updated to support "LevelledMobs" for "mob-level-plugin"

LevelledMobs: https://www.spigotmc.org/resources/levelledmobs-for-1-16-x-1-17-x.74304/

**Comment by CastedShadow** [comment]
Any progress on this front? Would love to see this be implemented.

**Comment by goflishMC** [comment]
spoke to the devs over at levelledmobs and they said they are going to add support from their end, so you might want to get with them and see what their progress is with implementing this
