### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BookWyrm114** [promcteam/prorpgitems#4]
**Describe the bug**
The plugin fails to load

**To Reproduce**
Start the server with the plugin installed, while running Purpur

**Expected behavior**
The plugin would load

**latest.log**
https://pastebin.com/02XsHh6H

**Versions (please complete the following information):**
-  Spigot Version: I am using a fork of paper known as "purpur"
 - Server Version: 1.16.5
 - Plugin Version : the latest version, not sure which version number, but I downloaded it from SpigotMC.

**Additional info**
The main plugin, (Proskillapi) did load, also I am using the "Goldencrates" plugin, which also used nexengine, perhaps that might be causing the problem?

**Comment by Laggypixel** [comment]
hi i had the same problem.
the solution is to download the plugins (core and the main one) from this site not from spigot
https://promcteam.com/marketplace/resources/prorpgitems-custom-items-creator.1/
https://promcteam.com/marketplace/resources/promccore-core-plugin-required-for-official-promcteam-plugins.2/
