### ISSUE TITLE
[Bug] Problem when using abilities

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#43]
When using abilities with the item gen it gives a message stating that the item is out of charges.

It sounds like the item gen is missing some settings that let you set the amount of charges that abilities can have.

Remove this "charge" restriction.

After this restriction is removed, make sure the cooldown message has a cooldown so that the user doesn't get spammed with the "ability on cooldown" message.

**Comment by Travja** [comment]
This has been resolved in new dev builds. Though can be worked around in older versions by adding the placeholder %ITEM_CHARGES% to the lore of the item being generated.
