### ISSUE TITLE
[Bug]: Empty lines under the lore of Set Bonuses can be copied

### ISSUE THREAD

**Issue by YKDZ** [promcteam/prorpgitems#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I change my Set Bonuses lore to this:

bonuses:
  by-elements-amount:
    '2':
      lore:
      - '%c%&lSet Bonuses (2/4):'
      - '%c%▸ +25% PvE Damage'
      - '%c%▸ +10 Max. Health'
      - '%c%▸ Speed I'
      - ''  # add one more empty line than the default setting
      
Then, in survival mode, wear any equipment in this sets on your body, then take it down in the inventory and wear it again. I can see that the empty line is constantly copying itself. By the way, this is my item_generator lore format:

 lore:
 - ''
 - '&7Tier: %TIER_NAME%'
 - '&7Level: &f%ITEM_LEVEL%'
 - '%ITEM_HAND%'
 - '%ITEM_AMMO%'
 - ''
 - '%ENCHANTS%'
 - '%GENERATOR_DEFENSE%'
 - '%GENERATOR_DAMAGE%'
 - '%GENERATOR_STATS%'
 - '%ITEM_SET%'
 - '%GENERATOR_SOCKETS_GEM%'
 - '%GENERATOR_SOCKETS_ESSENCE%'
 - '%GENERATOR_SOCKETS_RUNE%'
 - '%GENERATOR_ABILITY%'

### Steps To Reproduce

all above

### Environment

```markdown
- Server Software:Purpur 1.17.1 
- ProRPGItems Version: ProRPGItems-1.0.3.4-ALPHA
- ProMCCore Version: ProMCCore-1.0.3.1-ALPHA
- Plugins (101): ActionWords, AdvanceParticle, AuctionMaster, BankPlus, BestTools, BetterBees, BetterEggs, BetterTridents, BountyHunters, ChatManager, ChestSort, Citizens, CMI, CMILib, ColorBundles, ColorPortals, CombatLogX, Core, CoreProtect, CosmicVaults, CustomCrafting, DailyShop, DeluxeMenus, DoorsReloaded, eBackup, Elevator, ExplosionRegeneration, FartherViewDistance, GLight, GlowAPI*, GMusic, GoatHorn, GoldenChallenges, GoldenCrates, HeadDatabase, HoloChat*, HoloExtension, HolographicDisplays, ImageMaps, InvUnload, Iris, IronDoors*, ItemsAdder, Jobs, Lands, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MineableGems, MoneyPouch, MotionCaptureRewritten, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, NexEngine, NoOneFishing, NoOneRods, NPC_Destinations, NPCDestinations_Animator, PacketListenerApi, Parkour, PhatLoots, PlaceholderAPI, PlayerEmotesPro, PlayerTitle, PortableChests, PosePlugin, ProBlockRegen, ProMCCore, ProMCUtilities, ProRPGItems, ProtocolFirewall*, ProtocolLib, React*, RealisticSeasons, RiseCore, SelectionVisualizer, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, Skript, SortLoot2Inv, StarMail, StreakRewards, SurveyPlus, TitleManager, TradeMe, TrMenu, TroddenPath, Tweakin, UltimateDrugs, Vault, VeinMiner, WallJump, WanderingTrades, WolfyUtilities, WorldBorder, WorldEdit, XConomy, zAuctionHouseV3
```

### latest.log

no log

**Comment by goflishMC** [comment]
I just tested this several times, I can't get it to cause your issue. No new lines are created. Can you try removing all your other plugins except for prorpgitems, and promccore

**Comment by YKDZ** [comment]
> I just tested this several times, I can't get it to cause your issue. No new lines are created. Can you try removing all your other plugins except for prorpgitems, and promccore and then retest this.

I removed all plug-ins and tested them, but the problem still occurs. This is the GIF of the problem. 
https://imgur.com/a/BphuAFj

By the way, Can the other two issue I fed back be reproduced?

**Comment by goflishMC** [comment]
my bad, I only tested that with the item generator. I'll check that with sets.

**Comment by Travja** [comment]
Would the solution to this not just be to add an empty line in the item_generator configuration for the set? That way it's part of the item generator rather than the set?
