### ISSUE TITLE
[Bug]: All success rates are zero

### ISSUE THREAD

**Issue by YKDZ** [promcteam/prorpgitems#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

all item in module runes/gems/essence ‘s success rate lore is zero, but it still can work (success) . Like this:
![Snipaste_2021-10-03_09-36-30](https://user-images.githubusercontent.com/69898831/135736482-37c7acf5-8f2f-4e28-9c7a-aa461ce3d94d.png)
![Snipaste_2021-10-03_09-36-22](https://user-images.githubusercontent.com/69898831/135736483-cc8de207-a93e-443f-b91f-22704526d9e5.png)
![Snipaste_2021-10-03_09-36-26](https://user-images.githubusercontent.com/69898831/135736480-3103a57b-474c-4be8-8e69-1f7bd8a99d0f.png)
By the way, i use default item config

### Steps To Reproduce

1. install the plugin
2. use /gems(or runes/essence) to get an item
3. find the success rate is zero
4. get a equipment to use that gems
5. get a success

### Environment

```markdown
- Server Software: Purpur 1.17.1
- ProRPGItems Version: ProRPGItems-1.0.3.4-ALPHA
- ProMCCore Version: ProMCCore-1.0.3.1-ALPHA
- Plugins: CMI, CMILib, NoOneFishing, PlaceholderAPI, ProMCCore, ProRPGItems, ProtocolLib, Vault
```

### latest.log

no log

**Comment by goflishMC** [comment]
I tried testing this. I used 10 gems all had 0% chance to socket and they always fail.

https://i.imgur.com/dkyei14.gif

**Comment by YKDZ** [comment]
> I tried testing this. I used 10 gems all had 0% chance to socket and they always fail.
> 
> https://i.imgur.com/dkyei14.gif

I'm sorry, English is not my mother tongue, so I may have conveyed the wrong meaning to you. What I want to say is: the default configured gem will have a probability error (all are 0), but it still has a chance to be successfully used, like this:

https://imgur.com/a/KX8Lh2V

In my opinion, this is a display problem of probability during lore generation (it should not be 0) .

The probability configuration of gems is like this:

success-rate-by-level: # the probability is not 0
  '1': '75'
  '2': '35 * %ITEM_LEVEL%'
  '3': '30:50'
