### ISSUE TITLE
[Bug]: Refine item can not be used correctly

### ISSUE THREAD

**Issue by YKDZ** [promcteam/prorpgitems#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The behavior of the refine item is wrong, and it will not be consumed correctly. Like this:

https://imgur.com/a/89fc6sj

### Steps To Reproduce

1. install plugin
2. use /refine to get an refine item
3. refine an equipment
4. find the problem

### Environment

```markdown
- Server Software: Purpur 1.17.1
- ProRPGItems Version: ProRPGItems-1.0.3.4-ALPHA
- ProMCCore Version: ProMCCore-1.0.3.1-ALPHA
- Plugins: CMI, CMILib, NoOneFishing, PlaceholderAPI, ProMCCore, ProRPGItems, ProtocolLib, Vault
```

**Comment by Travja** [comment]
Should be resolved I believe with recent refine updates.
