### ISSUE TITLE
Lore requirements don't trigger language message or cancel event

### ISSUE THREAD

**Issue by mikk3612** [promcteam/prorpgitems#62]
It doesn't seem like lore requirements trigger the language message.

Tested with "Class" and "Required Level" type of lore. 

The attributes were not applied, but players could still "use" items (at least hold in their hand), but also able to use level 60 items if level 10, just no attributes.

It would be nice if this trigger the message in the language. Maybe add a config message "MessageNotUsable" so we can disable/enable.

event.SetCancelled(true) might also be needed? Just so you're not actually able to do anything with the item (like attack) or equip armor.

Thanks!

**Comment by goflishMC** [comment]
I think maybe you didn't add the class/level hooks to engine.yml
