### ISSUE TITLE
[Bug]: Errors on 1.18

### ISSUE THREAD

**Issue by redkk0523** [promcteam/prorpgitems#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

giving errors when performing commands on all modules 
for ex. /itemgen get will give error 
not only itemgen but afaik all modules does this 
this is the error im getting when using any command on a module 
https://pastebin.com/YsJ2mAeh

my server is 1.18 
![image](https://user-images.githubusercontent.com/92325343/145143037-765e0402-6214-4d24-95ac-6814fbfa3286.png)

also noticed something when i restarted the server 
![image](https://user-images.githubusercontent.com/92325343/145143085-fb935e6e-7cdc-4a32-9a87-48c32ba3461e.png)

also this thing is not working 
![image](https://user-images.githubusercontent.com/92325343/145143344-4e44d381-226d-4a90-8697-993548cd6592.png)

also all item generated from itemgen does not deal damage 
tested all weapon types axe swords hoes , bows and crossbows works though combat log doesnt work combat log is the damage display when dealing damage to an entity 

### Expected Behavior

functions should work as it is <3

### Steps To Reproduce

when you use commands in prorpgitems 

### Environment

```markdown
![image](https://user-images.githubusercontent.com/92325343/145143037-765e0402-6214-4d24-95ac-6814fbfa3286.png)
```

### latest.log

08.12 11:14:55 [Server] INFO KuyaKen issued server command: /drops give KuyaKen table_multi 1
08.12 11:15:10 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.setAccessible(boolean)" because "m" is null
08.12 11:15:10 [Server] WARN at ProMCCore-1.0.3.3-ALPHA.jar//mc.promcteam.engine.utils.Reflex.invokeMethod(Reflex.java:183)
08.12 11:15:10 [Server] WARN at ProMCCore-1.0.3.3-ALPHA.jar//mc.promcteam.engine.utils.reflection.Reflection_1_17.getAttributes(Reflection_1_17.java:276)
08.12 11:15:10 [Server] WARN at ProMCCore-1.0.3.3-ALPHA.jar//mc.promcteam.engine.utils.reflection.Reflection_1_17.getAttributeValue(Reflection_1_17.java:324)
08.12 11:15:10 [Server] WARN at ProMCCore-1.0.3.3-ALPHA.jar//mc.promcteam.engine.utils.reflection.Reflection_1_17.getDefaultArmor(Reflection_1_17.java:352)
08.12 11:15:10 [Server] WARN at ProMCCore-1.0.3.3-ALPHA.jar//mc.promcteam.engine.utils.reflection.ReflectionUtil.getDefaultArmor(ReflectionUtil.java:493)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.nms.engine.PMS.getDefaultArmor(PMS.java:28)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.stats.items.attributes.DefenseAttribute.getVanillaArmor(DefenseAttribute.java:99)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.stats.items.attributes.DefenseAttribute.get(DefenseAttribute.java:92)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.stats.items.ItemStats.getDefense(ItemStats.java:207)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.stats.EntityStats.getDefenseTypes(EntityStats.java:648)
08.12 11:15:10 [Server] WARN at ProRPGItems-1.0.3.9-ALPHA.jar//su.nightexpress.quantumrpg.manager.listener.object.VanillaWrapperListener.onVanillaDamage(VanillaWrapperListener.java:249)
08.12 11:15:10 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor715.execute(Unknown Source)
08.12 11:15:10 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
08.12 11:15:10 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
08.12 11:15:10 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
08.12 11:15:10 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
08.12 11:15:10 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247)
08.12 11:15:10 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1116)
08.12 11:15:10 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992)
08.12 11:15:10 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948)
08.12 11:15:10 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2041)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1345)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.animal.EntitySquid.a(EntitySquid.java:173)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.GlowSquid.a(GlowSquid.java:84)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.animal.axolotl.Axolotl.z(Axolotl.java:306)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.ai.behavior.BehaviorAttack.a(BehaviorAttack.java:50)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.ai.behavior.BehaviorAttack.a(BehaviorAttack.java:17)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.ai.behavior.Behavior.e(Behavior.java:61)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.ai.BehaviorController.d(BehaviorController.java:511)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.ai.BehaviorController.a(BehaviorController.java:470)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.animal.axolotl.Axolotl.R(Axolotl.java:282)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityInsentient.eE(EntityInsentient.java:865)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityLiving.w_(EntityLiving.java:3237)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityInsentient.w_(EntityInsentient.java:628)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityAgeable.w_(EntityAgeable.java:154)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.animal.EntityAnimal.w_(EntityAnimal.java:63)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2893)
08.12 11:15:10 [Server] WARN at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:396)
08.12 11:15:10 [Server] WARN at net.minecraft.server.level.WorldServer.a(WorldServer.java:1125)
08.12 11:15:10 [Server] WARN at net.minecraft.world.level.World.a(World.java:970)
08.12 11:15:10 [Server] WARN at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:667)
08.12 11:15:10 [Server] WARN at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
08.12 11:15:10 [Server] WARN at net.minecraft.server.level.WorldServer.a(WorldServer.java:647)
08.12 11:15:10 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1607)
08.12 11:15:10 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
08.12 11:15:10 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
08.12 11:15:10 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
08.12 11:15:10 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
08.12 11:15:10 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Travja** [comment]
Should be addressed in the latest build.
