### ISSUE TITLE
[Bug]: proRPGItems and handling of items/blocks

### ISSUE THREAD

**Issue by JetString** [promcteam/prorpgitems#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a bit complicated.
It seems that proRPGitems is "masking" all items so that they are not recognized anymore as whatever they are by other plugins.
One example would be my quests plugin. I have setup (without proRPGitems) a series of quests that require you to hand-in certain items. These quests are tested and work.
Now, as soon as i install proRPGitems, our quests plugin will not recognize the items as such anymore.
![questshandinitems](https://user-images.githubusercontent.com/95685462/147255349-63855bed-f964-4471-bdd9-87a3eb841250.png)

As you can see in the image.. I am trying to hand in 10 Oak logs, which are required by the quest, but when i try to hand the logs in, quests will tell me that (these) oak logs are not the one.

Now if I had farmed the Oak logs before I installed proRPGitems, I would still be able to hand them in! But because they were generated when proRPGitems was already installed they will not be recognized.

This also happens with MyPet. MyPet used the leash item to ride pets, when i generate the item when RPGitems is installed the item will not work (even when i uninstall RPGitems).
In order to have a working item, the item will have to be generated when RPGitems is NOT installed.

### Steps To Reproduce

install proRPG items
generate an item that is required by another plugin.
the item will not be recognized as such, and can therefor not be used.

### Environment

```markdown
- Server Software: 1.18.1 #99
- ProRPGItems Version: ProRPGItems-1.0.3.11-ALPHA
- ProMCCore Version: promccore-1.0.3.5-ALPHA
- Plugins:
50+
```

### latest.log

No error logs.

**Comment by JetString** [comment]
One more thing. Quite importantly!
If you want to test this. Quests will work if you set them up when proRPGitems is already installed.
SO in order to test this with quests, the quests will have to be setup BEFORE installing proRPGitems.
that's just generally how this behaves. i hope i made myself understood.

**Comment by JetString** [comment]
A very simple way to reproduce and proof the error.
take half a stack of dirt without proRPGitems installed
take half a stack of dirt from creative with proRPGitems installed.
The items do not stack together -> ergo they are somehow not the same.

**Comment by P-paj** [comment]
Didn't Notice at first, but this is probably the issue i recently reported.

The problem is that prorpgitems is putting this NBT data on every item: 
![image](https://user-images.githubusercontent.com/51720134/148139561-2b9b4925-dbab-4fef-83c5-ac6fcaefcd71.png)

**Comment by JetString** [comment]
oh this is done?
