### ISSUE TITLE
[Bug]: Crit Damage

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you have multiple items that boost critical damage its adding up incorrectly

Example: 2 items with 1.5x critical damage become 3x critical damage

### Expected Behavior

2 items with 1.5x critical damage to become 2x

2 solutions:

  - Adding -1 to all critical damage values before adding them up together and adding it back at the end so it becomes:
    1.5x + 1.5x => 0.5x + 0.5x = 1x => 2x
               removing 1          adding back 1
               
  - Turning critical damage into % where 1.5x will become 50% and it will be able to do additions without problems since:
    50% bonus damage + 50% bonus damage = 100% bonus damage
    

### Environment

```markdown
/
```

**Comment by goflishMC** [comment]
What trav mentioned in discord to resolve this was possibly not having it count the base 2x like 1.25 + 1.25, it should just be .25 + .25 or something like that.
