### ISSUE TITLE
[Enhancement] Attributes from Skillapi

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#83]
new file in item_stats/skillapi_attributes.yml

On startup the plugin would check for skillapi's attributes and automatically add them to "skillapi_attributes.yml" in "item_stats" directory using this format:

<pre>
intelligence:
  enabled: true
  name: Intelligence
  format: '&3▸ %name%: &f%value%'
  capacity: 10 # if set to -1 it disables the capacity check (see /item_stats/stats.yml for example)
</pre>

On startup the plugin would need to add (if skillapi attributes are detected) the available attributes placeholders that show in the lore to the item_generator module files

The range values for attributes can't be a range like other stats, it needs to be a number with no decimals (integer)

Example: If the user sets the minimum to 10 and the max to 40 it needs to be a an integer selected between those numbers, like "36"

<pre>
  skillapi-attributes:
    minimum: 1
    maximum: 2
    lore-format:
    - '%SKILLAPI_INTELLIGENCE%'
    - '%SKILLAPI_WISDOM%'
    - '%SKILLAPI_STRENGTH%'
    list:
      intelligence:
        chance: 100.0
        scale-by-level: 1.025
        min: 5
        max: 8
      wisdom:
        chance: 100.0
        scale-by-level: 1.025
        min: 5
        max: 8
      strength:
        chance: 100.0
        scale-by-level: 1.025
        min: 5
        max: 8
</pre>

In "engine.yml" add this if skillapi attributes are detected:

<pre>
      damage:
        format:
          single: '&f%value%'
</pre>

above:

<pre>
      skillapi_attributes:
        format:
          single: '&f%value%'
</pre>

A new option would also show up in the editor for this.

**Comment by Sentropic** [comment]
Solved by https://github.com/promcteam/prorpgitems/commit/01dba95b62c72e349c5c57f6731da383d37fa495, didn't see this issue before.
