### ISSUE TITLE
[Enhancement] Base Attack Speed Stat

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#85]
**Describe the solution you'd like**

A new stat called Base Attack Speed. It is a stat that sets the attack speed of the item based on damage per second (DPS):

  - Base Attack Speed: 1.6

* It can stack with the Attack Speed stat. 
* The stat should not be stackable with itself. 
* It only affects the held item in main hand.

**Comment by goflishMC** [comment]
There's a couple places where this would need to be addressed.

1. Create the new stat in item_generator module
2. Add the new stat In item_stats/stats.yml

**Comment by goflishMC** [comment]
@Sentropic Travja worked out the formula to get the damage per second here: https://www.promcteam.com/wiki/index.php/Prorpg:AttackSpeed

That's what this new feature would add. It makes it user friendly, that way they only need to set the DPS and not worrying about trying to work out this formula. It also looks dumb when your item says "-105%" for attack speed. 

With the original attack speed it can be used more as a small bonus or debuff to attack speed.

**Comment by lordsrubka5** [comment]
the original attack speed needs to be cleaned up as well so that it actually does what it says. If it says +10% attack speed it should be expected that it increases 10% of the base attack speed of the held item. I have to specifically state this since currently putting -99% attack speed on item just sets it to 1 or something close to that instead of going under that limit

Additionally as said above and I will repeat it again, It only checks that stat in main hand. If you have an item in offhand it will not affect anything, it will not add it on top of the main hand attack speed. If its armor then I guess its fine to add it since you would have to intentionally add it yourself and it would be intended otherwise you would swing twice as fast with dual wielding

**Comment by Sentropic** [comment]
https://github.com/promcteam/prorpgitems/commit/cb3354d06e21b242dd66d0e242f7a71cd6e9b5c9
Now adds base attack speed.
Regular attack speed now works as intented, for example:
If a sword has +1 Base Attack Speed and +10% Attack speed, it would end up with (1.6+1)*(1+0.1) = 2.86
