### ISSUE TITLE
[Bug] issue with item generation module

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgitems#9]
**Describe the bug**
For some reason some items if not all of them are getting the `{Amount: -1.0d, Slot: "mainhand", AttributeName: "minecraft:generic.attack_damage"}` nbt tag which nullifies the attack damage when you attempt hitting an entity.

Here's more info for reference: https://i.imgur.com/2b29rdO.png

Also, this issue is reference to ticket-0009 on discord.

**Comment by Travja** [comment]
@GreenTeaChaCha Updates on the damage stat will be posted here.
