### ISSUE TITLE
[Bug]: Plugin not recognizing classes

### ISSUE THREAD

**Issue by Shavick** [promcteam/prorpgitems#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i am a Human class and have set the requirements for items/consumables to require the Human class, but it is still saying that i am not the required class.

### Expected Behavior

I expect that i am able to use the items that require the class i have set in both proskillapi and prorpgitems

### Environment

```markdown
- Server Software: Shockbyte
- ProRPGItems Version: 1.0.3.12
- ProMCCore Version: 1.0.3.5
- Plugins: Proskillapi (latest version) proenchantmentapi (latest version)
```

**Comment by goflishMC** [comment]
you need to add proskillapi to engine.yml in progitems under the compatibility section.

**Comment by Shavick** [comment]
it is already there but it's as skillapi, does it need to be as proskillapi?

**Comment by Shavick** [comment]
it seems that having skillapi as the compatable plugin isnt good enough lol it works now that it's switched to "proskillapi" thank you very much @goflishMC
